[package]
name = "contexter"
version = "0.1.0"
edition = "2021"


[dependencies]
glob = "0.3.1"
clipboard-anywhere = "0.2.3"
clap = { version = "4.5.11", features = ["derive"] }
tempfile = "3.10.1"
ignore = "0.4.22"
regex = "1.10.5"
